/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kimia;

/**
 *
 * @author bayuirfan
 */
import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import kimia.data.CH;
import kimia.data.H;
import kimia.lib.Library;
import kimia.lib.LibraryView;
import kimia.ui.AboutDialog;
import kimia.ui.Alert;
import kimia.utils.CSVReader;
import kimia.utils.Constant;

public class Main extends javax.swing.JFrame implements LibraryView{

    /**
     * Creates new form Main
     */
    private final CardLayout mainPanel;
    private Library lib;
    private final ArrayList<CH> chArrayList = new ArrayList<>();
    private final ArrayList<H> hArrayList = new ArrayList();
    private final String CH_FILENAME = "ch";
    private final String H_FILENAME = "h";
    
    public Main() {
        initComponents();
        mainPanel = (CardLayout) (featuresPane.getLayout());
        progressBar.setVisible(false);
        progressHBar.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideMenu = new javax.swing.JPanel();
        sideMenuCHPanel = new javax.swing.JPanel();
        sideMenuCH = new javax.swing.JLabel();
        sideMenuHPanel = new javax.swing.JPanel();
        sideMenuH = new javax.swing.JLabel();
        featuresPane = new javax.swing.JPanel();
        cardCH = new javax.swing.JPanel();
        inputTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        chBox = new javax.swing.JCheckBox();
        ch2Box = new javax.swing.JCheckBox();
        processButton = new javax.swing.JButton();
        progressBar = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCH = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listCH2 = new javax.swing.JList<>();
        cardH = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inputHTextField = new javax.swing.JTextField();
        processHButton = new javax.swing.JButton();
        progressHBar = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listH = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(Constant.APP_NAME);
        setMinimumSize(new java.awt.Dimension(1000, 625));
        setName("mainFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1000, 625));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sideMenu.setBackground(new java.awt.Color(54, 70, 78));

        sideMenuCHPanel.setBackground(new java.awt.Color(54, 70, 78));
        sideMenuCHPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sideMenuCHPanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sideMenuCHPanelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sideMenuCHPanelMouseEntered(evt);
            }
        });

        sideMenuCH.setForeground(new java.awt.Color(255, 255, 255));
        sideMenuCH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sideMenuCH.setText("CH");
        sideMenuCH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout sideMenuCHPanelLayout = new javax.swing.GroupLayout(sideMenuCHPanel);
        sideMenuCHPanel.setLayout(sideMenuCHPanelLayout);
        sideMenuCHPanelLayout.setHorizontalGroup(
            sideMenuCHPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideMenuCH, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        sideMenuCHPanelLayout.setVerticalGroup(
            sideMenuCHPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideMenuCH, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        sideMenuHPanel.setBackground(new java.awt.Color(54, 70, 78));
        sideMenuHPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sideMenuHPanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sideMenuHPanelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sideMenuHPanelMouseEntered(evt);
            }
        });

        sideMenuH.setForeground(new java.awt.Color(255, 255, 255));
        sideMenuH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sideMenuH.setText("H");
        sideMenuH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout sideMenuHPanelLayout = new javax.swing.GroupLayout(sideMenuHPanel);
        sideMenuHPanel.setLayout(sideMenuHPanelLayout);
        sideMenuHPanelLayout.setHorizontalGroup(
            sideMenuHPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideMenuH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sideMenuHPanelLayout.setVerticalGroup(
            sideMenuHPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideMenuH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout sideMenuLayout = new javax.swing.GroupLayout(sideMenu);
        sideMenu.setLayout(sideMenuLayout);
        sideMenuLayout.setHorizontalGroup(
            sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideMenuCHPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sideMenuHPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sideMenuLayout.setVerticalGroup(
            sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sideMenuCHPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sideMenuHPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(426, Short.MAX_VALUE))
        );

        sideMenuCHPanel.getAccessibleContext().setAccessibleName("sideMenu1");
        sideMenuHPanel.getAccessibleContext().setAccessibleName("sideMenu2");

        getContentPane().add(sideMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 552));

        featuresPane.setLayout(new java.awt.CardLayout());

        inputTextField.setToolTipText("Gunakan Titik untuk memberikan koma pada input");

        jLabel3.setText("Input Data");
        jLabel3.setToolTipText("");

        jLabel4.setText("Kelompok Pergeseran");

        chBox.setText("CH");

        ch2Box.setText("CH2");

        processButton.setText("Proses");
        processButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processButtonActionPerformed(evt);
            }
        });

        progressBar.setName(""); // NOI18N

        jLabel5.setText("Hasil Prediksi");

        jLabel6.setText("Kelompok CH");

        listCH.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        listCH.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listCH);

        jLabel7.setText("Kelompok CH2");

        listCH2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        listCH2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(listCH2);

        javax.swing.GroupLayout cardCHLayout = new javax.swing.GroupLayout(cardCH);
        cardCH.setLayout(cardCHLayout);
        cardCHLayout.setHorizontalGroup(
            cardCHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardCHLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(cardCHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(processButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputTextField)
                    .addGroup(cardCHLayout.createSequentialGroup()
                        .addGroup(cardCHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cardCHLayout.createSequentialGroup()
                                .addComponent(chBox)
                                .addGap(58, 58, 58)
                                .addComponent(ch2Box))
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(0, 111, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(cardCHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(cardCHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(cardCHLayout.createSequentialGroup()
                            .addComponent(jScrollPane2)
                            .addContainerGap())
                        .addComponent(jLabel6)
                        .addGroup(cardCHLayout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardCHLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(139, 139, 139)))))
        );
        cardCHLayout.setVerticalGroup(
            cardCHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardCHLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardCHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cardCHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardCHLayout.createSequentialGroup()
                        .addComponent(inputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(cardCHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chBox)
                            .addComponent(ch2Box))
                        .addGap(18, 18, 18)
                        .addComponent(processButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cardCHLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        inputTextField.getAccessibleContext().setAccessibleName("inputTextField");
        jLabel3.getAccessibleContext().setAccessibleName("inputLabel");
        chBox.getAccessibleContext().setAccessibleName("chBox");
        ch2Box.getAccessibleContext().setAccessibleName("ch2Box");
        processButton.getAccessibleContext().setAccessibleName("processButton");

        featuresPane.add(cardCH, "featuresCH");
        cardCH.getAccessibleContext().setAccessibleName("featuresCH");

        jLabel1.setText("Input Data");

        inputHTextField.setToolTipText("Gunakan titik untuk memberikan koma pada input");

        processHButton.setText("Proses");
        processHButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processHButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Hasil Prediksi");

        listH.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(listH);

        javax.swing.GroupLayout cardHLayout = new javax.swing.GroupLayout(cardH);
        cardH.setLayout(cardHLayout);
        cardHLayout.setHorizontalGroup(
            cardHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardHLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(cardHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardHLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(processHButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(progressHBar, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                    .addComponent(inputHTextField))
                .addGap(12, 12, 12)
                .addGroup(cardHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardHLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(142, 142, 142))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardHLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        cardHLayout.setVerticalGroup(
            cardHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardHLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cardHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardHLayout.createSequentialGroup()
                        .addComponent(inputHTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(processHButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(progressHBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE))
                .addContainerGap())
        );

        featuresPane.add(cardH, "featuresH");
        cardH.getAccessibleContext().setAccessibleName("featuresH");
        cardH.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(featuresPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 710, 490));
        featuresPane.getAccessibleContext().setAccessibleName("featuresPanel");

        jMenu1.setText("File");
        jMenu1.setName("fileMenu"); // NOI18N

        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(aboutMenuItem);

        jMenuBar1.add(jMenu1);
        jMenu1.getAccessibleContext().setAccessibleName("fileMenu");

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void processButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processButtonActionPerformed
        // TODO add your handling code here:
        progressBar.setVisible(true);
        if (inputTextField.getText().equalsIgnoreCase("")){
            Alert.showDialog("Alert", "Input harus diisi");
        } else if (!ch2Box.isSelected() && !chBox.isSelected()){
            Alert.showDialog("Alert", "Pilih mode prediksi");
        } else {
            lib = new Library(this);
            chArrayList.clear();
            chArrayList.addAll(CSVReader.loadCHData(CH_FILENAME));
            double input = Double.parseDouble(inputTextField.getText());

            if (chBox.isSelected()){
                ArrayList<CH> resultCH = new ArrayList<>();
                resultCH.addAll(lib.predictCH(input, chArrayList));
                DefaultListModel<String> ch = new DefaultListModel<>();
                for (int i = 0; i < resultCH.size(); i++) {
                    ch.add(i, "CH" + resultCH.get(i).getR());
                }
                listCH.setModel(ch);
            }

            if (ch2Box.isSelected()){
                ArrayList<CH> resultCH2 = new ArrayList<>();
                resultCH2.addAll(lib.predictCH2(input, chArrayList));
                DefaultListModel<String> ch = new DefaultListModel<>();
                for (int i = 0; i < resultCH2.size(); i++){
                    ch.add(i, "CH2" + resultCH2.get(i).getR());
                }
                listCH2.setModel(ch);
            }
        }
        progressBar.setVisible(false);
    }//GEN-LAST:event_processButtonActionPerformed

    private void sideMenuHPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sideMenuHPanelMouseClicked
        // TODO add your handling code here:
        mainPanel.show(featuresPane, "featuresH");
    }//GEN-LAST:event_sideMenuHPanelMouseClicked

    private void sideMenuCHPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sideMenuCHPanelMouseClicked
        // TODO add your handling code here:
        mainPanel.show(featuresPane, "featuresCH");
    }//GEN-LAST:event_sideMenuCHPanelMouseClicked

    private void sideMenuCHPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sideMenuCHPanelMouseEntered
        // TODO add your handling code here:
        sideMenuCHPanel.setBackground(Color.decode("#7E8987"));
    }//GEN-LAST:event_sideMenuCHPanelMouseEntered

    private void sideMenuHPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sideMenuHPanelMouseEntered
        // TODO add your handling code here:
        sideMenuHPanel.setBackground(Color.decode("#7E8987"));
    }//GEN-LAST:event_sideMenuHPanelMouseEntered

    private void sideMenuHPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sideMenuHPanelMouseExited
        // TODO add your handling code here:
        sideMenuHPanel.setBackground(Color.decode("#36464E"));
    }//GEN-LAST:event_sideMenuHPanelMouseExited

    private void sideMenuCHPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sideMenuCHPanelMouseExited
        // TODO add your handling code here:
        sideMenuCHPanel.setBackground(Color.decode("#36464E"));
    }//GEN-LAST:event_sideMenuCHPanelMouseExited

    private void processHButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processHButtonActionPerformed
        // TODO add your handling code here:
        progressHBar.setVisible(true);
        if (inputHTextField.getText().equalsIgnoreCase("")){
            Alert.showDialog("Alert", "Input harus diisi");
        } else {
            lib = new Library(this);
            hArrayList.clear();
            hArrayList.addAll(CSVReader.loadHData(H_FILENAME));
            double input = Double.parseDouble(inputHTextField.getText());
            
            ArrayList<H> resultH = new ArrayList<>();
            resultH.addAll(lib.predictCisTransGem(input, hArrayList));
            DefaultListModel<String> h = new DefaultListModel<>();
            for (int i = 0; i < resultH.size(); i++) {
                h.add(i, "H" + resultH.get(i).getR());
            }
            listH.setModel(h);
        }
        progressHBar.setVisible(false);
    }//GEN-LAST:event_processHButtonActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        // TODO add your handling code here:
        AboutDialog.showDialog();
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JPanel cardCH;
    private javax.swing.JPanel cardH;
    private javax.swing.JCheckBox ch2Box;
    private javax.swing.JCheckBox chBox;
    private javax.swing.JPanel featuresPane;
    private javax.swing.JTextField inputHTextField;
    private javax.swing.JTextField inputTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listCH;
    private javax.swing.JList<String> listCH2;
    private javax.swing.JList<String> listH;
    private javax.swing.JButton processButton;
    private javax.swing.JButton processHButton;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JProgressBar progressHBar;
    private javax.swing.JPanel sideMenu;
    private javax.swing.JLabel sideMenuCH;
    private javax.swing.JPanel sideMenuCHPanel;
    private javax.swing.JLabel sideMenuH;
    private javax.swing.JPanel sideMenuHPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateProgressCH(int progress) {
        progressBar.setValue(progress);
    }

    @Override
    public void updateProgressH(int progress) {
        progressHBar.setValue(progress);
    }
}
